# This file was generated by GoReleaser. DO NOT EDIT.
cask "baryon-mcp" do
  version "0.4.11"

  on_macos do
    on_intel do
      sha256 "a6a8f5807c78a6e465275f6212a6df7afd24d4f808a8e1e7eec22ea98b0eedd0"
      url "https://github.com/combor/baryon-mcp/releases/download/v#{version}/baryon-mcp_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "02feb8e41ba7e9c68ad762f3c641e99d1e8a42747978772e056656fbd0e99213"
      url "https://github.com/combor/baryon-mcp/releases/download/v#{version}/baryon-mcp_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "da36892b3b44645b56b117ddc70edc7edc68ceca4fd9ac3390eb734029d036e9"
      url "https://github.com/combor/baryon-mcp/releases/download/v#{version}/baryon-mcp_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "964d817074513240165110b44fb1ff3c070107c987be5a7e1796e40f4b1cd13b"
      url "https://github.com/combor/baryon-mcp/releases/download/v#{version}/baryon-mcp_#{version}_linux_arm64.tar.gz"
    end
  end

  name "baryon-mcp"
  desc "Read Proton Mail and save drafts through your local Proton Mail Bridge."
  homepage "https://github.com/combor/baryon-mcp"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "baryon-mcp"

  # No zap stanza required

end
