# This file was generated by GoReleaser. DO NOT EDIT.
cask "baryon-mcp" do
  version "0.4.6"

  on_macos do
    on_intel do
      sha256 "ae5ed339887abc55ac7328c9dd8697205327faad8f0f0096e7d14bada8405238"
      url "https://github.com/combor/baryon-mcp/releases/download/v#{version}/baryon-mcp_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "de2528356850bb5fe28ec1030c3bdb951ed65e5db0cfeb11f0d8d399795a7bf9"
      url "https://github.com/combor/baryon-mcp/releases/download/v#{version}/baryon-mcp_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "e61c6cf06a538302ab1bd7193ff94bf6c134b905f5e8512e60e740a7fa19405a"
      url "https://github.com/combor/baryon-mcp/releases/download/v#{version}/baryon-mcp_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "d071697fd255309580d38b8738c5dec8fafac8779e7e304e6494f9535c8d7074"
      url "https://github.com/combor/baryon-mcp/releases/download/v#{version}/baryon-mcp_#{version}_linux_arm64.tar.gz"
    end
  end

  name "baryon-mcp"
  desc "Read Proton Mail and save drafts through your local Proton Mail Bridge."
  homepage "https://github.com/combor/baryon-mcp"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "baryon-mcp"

  # No zap stanza required

end
