# This file was generated by GoReleaser. DO NOT EDIT.
cask "baryon-mcp" do
  version "0.6.3"

  on_macos do
    on_arm do
      sha256 "6f41e76a9503a876fdaeb0c33e49b431d770d1c568110889ddb13efd6ca96c65"
      url "https://github.com/combor/baryon-mcp/releases/download/v#{version}/baryon-mcp_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "8b14bf591fddc73b58bb5efd145414f77a29282e6ff0f65225f4527d0c432afe"
      url "https://github.com/combor/baryon-mcp/releases/download/v#{version}/baryon-mcp_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "3830a6e429cf0e56a8c1a48c8350b320ce519d9cc8c4fb81601bc9cfe33419f9"
      url "https://github.com/combor/baryon-mcp/releases/download/v#{version}/baryon-mcp_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "c90608ef1eaaf59bd4559ce29be34250bd653214a98ece56d7df9e030afd6ba9"
      url "https://github.com/combor/baryon-mcp/releases/download/v#{version}/baryon-mcp_#{version}_linux_amd64.tar.gz"
    end
  end

  name "baryon-mcp"
  desc "Read Proton Mail and save drafts through your local Proton Mail Bridge."
  homepage "https://github.com/combor/baryon-mcp"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "baryon-mcp"

  # No zap stanza required
end
