# This file was generated by GoReleaser. DO NOT EDIT.
cask "magnetowid" do
  version "0.3.0"

  on_macos do
    on_arm do
      sha256 "06839e67da6ad0752be0c647f6c4804ccf0cd1b74c73eaf034a9b4fb60ea7557"
      url "https://github.com/combor/magnetowid/releases/download/v#{version}/magnetowid_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "7ed0c09fd47dd00acd8fd8fc2b8afd8f4f312bf38a55fea28d2887f71506abc5"
      url "https://github.com/combor/magnetowid/releases/download/v#{version}/magnetowid_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "9ca5c1dfbd2067475dd0e36d6f38b66854929625084e42663aa6c1299f4eba4f"
      url "https://github.com/combor/magnetowid/releases/download/v#{version}/magnetowid_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "a1c0b0f8e631509122f39a36bfefe89e4076ead0d355942901de4c475be634f4"
      url "https://github.com/combor/magnetowid/releases/download/v#{version}/magnetowid_#{version}_linux_amd64.tar.gz"
    end
  end

  name "magnetowid"
  desc "Downloads movies and series from video-on-demand sites for Sonarr and Radarr."
  homepage "https://github.com/combor/magnetowid"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "ffmpeg",
    ]

  binary "magnetowid"

  # No zap stanza required
end
