# This file was generated by GoReleaser. DO NOT EDIT.
cask "magnetowid" do
  version "0.4.0"

  on_macos do
    on_arm do
      sha256 "15878f419f7fbbe77958ec4f9c0e799bfa9b4f57712abe16b69becbcc2ae4fb9"
      url "https://github.com/combor/magnetowid/releases/download/v#{version}/magnetowid_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "42a938e63b8d18db60d1e7991aac7449676b9f04e75b136d45368ca0f8fda11f"
      url "https://github.com/combor/magnetowid/releases/download/v#{version}/magnetowid_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "8d7d8652d2feb99e6a8294fe7160c3d80ef2b9f19c3f57eb69d9f71ec7b78d1d"
      url "https://github.com/combor/magnetowid/releases/download/v#{version}/magnetowid_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "d7593f7f546c2b90481d2b41f86f03418b825513c6ebdcac2b9ff2c5a359eaeb"
      url "https://github.com/combor/magnetowid/releases/download/v#{version}/magnetowid_#{version}_linux_amd64.tar.gz"
    end
  end

  name "magnetowid"
  desc "Downloads movies and series from video-on-demand sites for Sonarr and Radarr."
  homepage "https://github.com/combor/magnetowid"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "ffmpeg",
    ]

  binary "magnetowid"

  # No zap stanza required
end
