# This file was generated by GoReleaser. DO NOT EDIT.
cask "magnetowid" do
  version "0.4.1"

  on_macos do
    on_arm do
      sha256 "aaf1f634af2a491e786a700b582ed09fc09377a43ffa111cadf5510533acb20c"
      url "https://github.com/combor/magnetowid/releases/download/v#{version}/magnetowid_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "eb26b99873d8a8b9fd3fb3553194ce307a514342cee16db0eed417a55f9a7505"
      url "https://github.com/combor/magnetowid/releases/download/v#{version}/magnetowid_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "9e76fa4b7813fa1f2a6375e117b39ee1992233ae9c5257700ed7b775c9312457"
      url "https://github.com/combor/magnetowid/releases/download/v#{version}/magnetowid_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "8f8c1d41c9de4237ed1eaac36c7a8cd49979539e3849bd43037fe19bca720d7f"
      url "https://github.com/combor/magnetowid/releases/download/v#{version}/magnetowid_#{version}_linux_amd64.tar.gz"
    end
  end

  name "magnetowid"
  desc "Downloads movies and series from video-on-demand sites for Sonarr and Radarr."
  homepage "https://github.com/combor/magnetowid"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "ffmpeg",
    ]

  binary "magnetowid"

  # No zap stanza required
end
