# This file was generated by GoReleaser. DO NOT EDIT.
cask "telesfor" do
  version "0.2.4"

  on_macos do
    on_arm do
      sha256 "ce6348139015dba2c52f0d8caf93522801425221c0166aa9a616f9002d318f5c"
      url "https://github.com/combor/telesfor/releases/download/v#{version}/telesfor_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "fab8ad736ebd9e59da8e8e57b8e32e7b094d8eebc36f541fa9e1fbbbb557b7d5"
      url "https://github.com/combor/telesfor/releases/download/v#{version}/telesfor_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "fccbaecf4056da490f34e4e346d7d7cc21d99c74589965a67dc30814bf7e71aa"
      url "https://github.com/combor/telesfor/releases/download/v#{version}/telesfor_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "c9068ddf9eb8111351ff2b3463885b3afc82a9ac16da0c75dd5b0aba3dca3faa"
      url "https://github.com/combor/telesfor/releases/download/v#{version}/telesfor_#{version}_linux_amd64.tar.gz"
    end
  end

  name "telesfor"
  desc "Live TV from streaming services in Plex, as a virtual HDHomeRun tuner."
  homepage "https://github.com/combor/telesfor"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "ffmpeg",
    ]

  binary "telesfor"

  # No zap stanza required
end
