# This file was generated by GoReleaser. DO NOT EDIT.
cask "telesfor" do
  version "0.2.6"

  on_macos do
    on_arm do
      sha256 "51fb11c2ce576e1076d1da03c1deb131c68a453bb75315bd696d3aaaef6d6a89"
      url "https://github.com/combor/telesfor/releases/download/v#{version}/telesfor_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "283f0e8d838f81f47fdb28123cfa1f6129bc4b86efb319c6842bf0e6b9405824"
      url "https://github.com/combor/telesfor/releases/download/v#{version}/telesfor_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "f7f55d05946898db980065b94a283f18415906408063b4b2c25b82479fb1bcde"
      url "https://github.com/combor/telesfor/releases/download/v#{version}/telesfor_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "87974f94a0c3bea00e33a12204418f4240c07f7b06c08f27117a397b5659e697"
      url "https://github.com/combor/telesfor/releases/download/v#{version}/telesfor_#{version}_linux_amd64.tar.gz"
    end
  end

  name "telesfor"
  desc "Live TV from streaming services in Plex, as a virtual HDHomeRun tuner."
  homepage "https://github.com/combor/telesfor"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "ffmpeg",
    ]

  binary "telesfor"

  # No zap stanza required
end
