# This file was generated by GoReleaser. DO NOT EDIT.
cask "telesfor" do
  version "0.3.0"

  on_macos do
    on_arm do
      sha256 "ef9565f79c99a85a6a5bc7ffa425bce07625da2ef87abe6ba076a68e90480fcf"
      url "https://github.com/combor/telesfor/releases/download/v#{version}/telesfor_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "8857d8b28f94c1900096faba78f77b6bfd25f35a02dfbcea8859cbfc5020371d"
      url "https://github.com/combor/telesfor/releases/download/v#{version}/telesfor_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "c00ae1f6369ebed841483416cc16a0f16f104d0921aae44d0869c45c64236c72"
      url "https://github.com/combor/telesfor/releases/download/v#{version}/telesfor_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "65d26d954c766482a08360add7613d05d65926c6071e5021cb2fac0a2427fe84"
      url "https://github.com/combor/telesfor/releases/download/v#{version}/telesfor_#{version}_linux_amd64.tar.gz"
    end
  end

  name "telesfor"
  desc "Live TV from streaming services in Plex, as a virtual HDHomeRun tuner."
  homepage "https://github.com/combor/telesfor"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "ffmpeg",
    ]

  binary "telesfor"

  # No zap stanza required
end
