# This file was generated by GoReleaser. DO NOT EDIT.
cask "vodarr" do
  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "dd2f6e663bc2898534c9e114596c2e2f4b1e9a03032e8bec7577938ebb045e10"
      url "https://github.com/combor/vodarr/releases/download/v#{version}/vodarr_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "9dc8d1184397a3d492d2fd6b0c304f46ce496124ae15d6ed6864dd0944b8d761"
      url "https://github.com/combor/vodarr/releases/download/v#{version}/vodarr_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "10da6de0ce51214bc147b250314589e4a8ae6fc203cc0ce9677a8603465c2355"
      url "https://github.com/combor/vodarr/releases/download/v#{version}/vodarr_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "e1f9ec400fbd0f2bf2c5f2ee4f3aa8ac32b4245ebf11d0d54a1ccb65e4673093"
      url "https://github.com/combor/vodarr/releases/download/v#{version}/vodarr_#{version}_linux_amd64.tar.gz"
    end
  end

  name "vodarr"
  desc "Downloads movies and series from video-on-demand sites for Sonarr and Radarr."
  homepage "https://github.com/combor/vodarr"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "ffmpeg",
    ]

  binary "vodarr"

  # No zap stanza required
end
