# This file was generated by GoReleaser. DO NOT EDIT.
cask "vodarr" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "fa940fd5735df44005d4ba176e526f7b7ce283c4d4e58e38ef4de07121ae31e3"
      url "https://github.com/combor/vodarr/releases/download/v#{version}/vodarr_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "6b89620b3b5b306021dcc712dd294c170bf438de74fd4551a5c99dd57cd3cc71"
      url "https://github.com/combor/vodarr/releases/download/v#{version}/vodarr_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "be5180206484bfee25a11865a4c040240a3fc4bbceb9eb79b5d55d79025a0ec8"
      url "https://github.com/combor/vodarr/releases/download/v#{version}/vodarr_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "24bf9db87574abab97b67681cf92f680307174b88fa5159045d07990b3d93bcf"
      url "https://github.com/combor/vodarr/releases/download/v#{version}/vodarr_#{version}_linux_amd64.tar.gz"
    end
  end

  name "vodarr"
  desc "Downloads movies and series from video-on-demand sites for Sonarr and Radarr."
  homepage "https://github.com/combor/vodarr"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "ffmpeg",
    ]

  binary "vodarr"

  # No zap stanza required
end
